# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jéssica Carneiro
email: jessicacarneiro@ufmg.br
description: > # this means to ignore newlines until "site.github.url:"
  A blog about technology, programming, Internet, languages
  and more!
site.github.url: "http://jessicacarneiro.github.io" # the base hostname & protocol for your site
twitter_username: jessicacarneir0
github_username:  jessicacarneiro

# Build settings
markdown: kramdown

# plugins
gems: []
